### ISSUE TITLE
name 'datetime' is not defined on docker server side

### ISSUE THREAD

**Issue by ugofiasconaro** [gmag11/MetaTrader5-Docker-Image#4]
Hi I have problem of datetime on the docker server side as I show you on the attached screenshot. 
Do You Know what the problem could be? Thank You.

![Screenshot 2024-04-26 231854](https://github.com/gmag11/MetaTrader5-Docker-Image/assets/121483277/c5071d9d-26a5-4219-b128-de4528967108)

Best Regards.

**Comment by ugofiasconaro** [comment]
Hi,
I have reached my goal by replacing the following python method:

From this:     mt5.copy_rates_from('EURUSD',mt.TIMEFRAME_D1,utc_from,10)
To this:          mt5.copy_rates_from_pos('EURUSD',mt.TIMEFRAME_D1,0,10)

Thank You.
Best Regards.

**Comment by gmag11** [comment]
Thank you for sharing

**Comment by lucas-campagna** [comment]
Run this `mt5.exec("import datetime")`
