### ISSUE TITLE
How to secure python RPyC and vnc

### ISSUE THREAD

**Issue by atmarammuduli** [gmag11/MetaTrader5-Docker-Image#7]
Please guide how to secure RPyC using header or any other method. Also need to understand how vnc is password protected

**Comment by gmag11** [comment]
Yes, you can add a password to the service, this is explained in Readme file.

Protecting your instance is out of the scope of this project. There are so many ways to achieve and depend on your use, requirements, setup, etc.

Anyway, you should NEVER expose this to the Internet even if it has a password. Using a VPN at least should be a must for this service.
