### ISSUE TITLE
Run multiple containers in same time

### ISSUE THREAD

**Issue by billythekidz** [gmag11/MetaTrader5-Docker-Image#8]
I have issue when try to run more than one container.
Only 1 MT5 terminal can open, another tab is can not show MT5 terminal. I'm try to restart this docker container, It will show but the first one is gone :(
I'm using config like this to run another port:

> version: '3'
services:
  mt5-2:
    image: gmag11/metatrader5_vnc:1.0
    container_name: mt5-2
    volumes:
      - ./config:/config
    ports:
      - 3001:3000
      - 8002:8001
    environment:
      - CUSTOM_USER=
      - PASSWORD=

      
Can you give me advise?

**Comment by gmag11** [comment]
Hi, may you paste your complete docker compose file with multiple instances?

**Comment by billythekidz** [comment]
> version: '3'
services:
  mt5-1:
    image: gmag11/metatrader5_vnc:1.0
    container_name: mt5-1
    volumes:
      - ./config1:/config
    ports:
      - 3000:3000
      - 8001:8001
    environment:
      - CUSTOM_USER=
      - PASSWORD=

  mt5-2:
    image: gmag11/metatrader5_vnc:1.0
    container_name: mt5-2
    volumes:
      - ./config2:/config
    ports:
      - 3001:3000
      - 8002:8001
    environment:
      - CUSTOM_USER=
      - PASSWORD=

Hi, this is my compose file. 

I already solve the issue!
No problem with multiple instances. The reason is my ram too small. 
It's require at least 1gb ram per instance.
Thank @gmag11  your image can help me to run multiple MT5 terminals with lower cost.
